openapi: 3.0.3
info:
  title: MANGER CE
  description: Platillos Mexicanos
  termsOfService: http://swagger.io/terms/
  contact:
    email:  MangerCE@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://MangerCe.swagger.io/api/v3
tags:
  - name: Dish
    description: Everything about your Dish
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: Manger Ce
    description: Access to Dish orders
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io
  - name: user
    description: Operations about user


paths:
  /:
   post:
     tags:
     - Dish
     summary: Insert new Dishes in the Data Base
     parameters:
     - $ref: '#/components/parameters/Dish'
     requestBody:
       content:
         application/json:
           schema:
             $ref: '#/components/schemas/BodyDishPost'
       required: true
     responses:
       200:
         description: The new Dish has been sumbit Succesfully
         content:
          application/json:
           schema:
            $ref: '#/components/schemas/SuccesfullDish'
            
       400:
         $ref: '#/components/responses/BadRequest'
         
       401:
         $ref: '#/components/responses/DishAlreadyinTheDB'
        
       404:
         $ref: '#/components/responses/NoInformation'
         
 
               
       
components:
    responses:
     DishAlreadyinTheDB:
      description: Dish is already in the DataBase
      
     NoInformation:
      description: Information not Found
      
     BadRequest:
      description: The Data sent was incorrect
      
    parameters:
      Dish:
        in: header
        description: Dish autenticator
        required: true
    schemas:
      BodyDishPost:
        type: object
        properties: 
          Name of the Dish:
           type: string
           description: Put the name of the new Dish
          Type of Dish:
           type: string
           description: Put the type of Dish, if is a taco or a soup
      
      SuccesfullDish:
        type: object
        properties:
         respuesta:
          type: integer
          enum: [1]
          description: Type of flag that tell us if the new dish was added
         idDish:
           type: integer
           enum: [98]
           description: The ID of the new Dish
           
      SuccesfullDishGet:
       type: object
       properties:
         Name of the Dish:
           type: string
           description: Put the name of the new Dish
         Type of Dish:
           type: string
           description: Put the type of Dish, if is a taco or a soup